---
# install debian packages
- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "update_cache"


- name: upgrade deb packages
  become: yes
  apt:
    upgrade: dist
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "upgrade"

- name: install deb package
  become: yes
  apt: name="{{ item }}" state="{{ pkg_state | default('latest'}}"
  with_items:
    - "{{ pkgs['deb'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "install"
