---
# install debian packages
- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  tags:
    - update_cache

- name: upgrade deb packages
  become: yes
  apt:
    upgrade: dist
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  tags:
    - upgrade

- name: install deb package
  become: yes
  apt: name="{{ item }}" state="{{ pkg_state }}"
  with_items:
    - "{{ pkgs['deb'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  tags:
    - install
