---
# install debian packages

- name: install deb package
  become: yes
  apt: name="{{ item }}" state="{{ pkg_state }}"
  with_items:
    - "{{ pkgs['deb'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
