---
# install debian packages

- name: install deb package
  apt: name="{{ item }}" state="{{ freckles_pkg_state }}"
  with_items:
    - "{{ freckles_pkgs['deb'] | default(freckles_pkgs['default']) }}"
