---
# tasks file for ansible-freckles
# - name: dump all
  # action: template src=templates/dumpall.j2 dest=/tmp/ansible.all

# - name: debug
  # debug: msg="{{ item }}"
  # with_items:
    # - "{{ freckles_pkgs }}"

- name: Current application
  debug: var=freckles_app_name

- include: deb.yml
  when: (freckles_pkg_mgr is defined and freckles_pkg_mgr == 'deb') or (freckles_pkg_mgr is not defined and ansible_os_family == "Debian")

- include: rpm.yml
  when: (freckles_pkg_mgr is defined and freckles_pkg_mgr == 'rpm') or (freckles_pkg_mgr is not defined and ansible_os_family == "RedHat")

- include: nix.yml
  when: freckles_pkg_mgr is defined and freckles_pkg_mgr == 'nix'
