---
# yum doesn't have a meaningful update_cache mechanism, as far as I can see
- name: upgrade all rpm packages
  become: yes
  yum:
    name: '*'
    state: latest
  when: install_action == "upgrade"

- name: install rpm package
  become: yes
  yum: name="{{ item }}" state="{{ pkg_state | default(latest) }}"
  with_items:
    - "{{ pkgs['rpm'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "install"
